eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@localhost:8761/eureka
server:
  port: 8000

app:
  security:
    private-key: 123456

spring:
  cloud:
    gateway:
      routes:
        - id: main-backend
          uri: lb://main-backend
          predicates:
            - Path=/users/**,/user/**,/notifications/**,/v3/schedules/**,/v3/schedule/**,/schedule/**
          filters:
            - TelegramBotAuthFilter
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/test/notifications/**
          filters:
            - TelegramBotAuthFilter
            - StripPrefix=2
    config:
      enabled: true
  config:
    import: optional:configserver:http://localhost:8888
debug: true


