eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@localhost:8761/eureka
server:
  port: 8000

app:
  security:
    private-key: 123456


spring:
  cloud:
    gateway:
      routes:
        - id: main-backend
          uri: lb://main-backend
          predicates:
            - Path=/users/**,/user/**,/notifications/**,/v3/schedules/**,/v3/schedule/**,/schedule/**
          filters:
            - TelegramBotAuthFilter
debug: true

