eureka:
  client:
    service-url:
      defaultZone: ${SERVICE_DISCOVERY_URL}
server:
  port: ${SERVER_PORT:8000}
spring:
  cloud:
    config:
      fail-fast: true
  config:
    import: configserver:${CONFIG_SERVER}

